### ISSUE TITLE
Gnome 45

### ISSUE THREAD

**Issue by fastrizwaan** [jkitching/soft-brightness-plus#10]
Hi @jkitching 

Would it be possible to make this extension work with gnome 45. I would really appreciate your time efforts. Thanks.

**Comment by nahuelpucciarelli** [comment]
This would be awesome. It's the only extension that works with my monitor

**Comment by jkitching** [comment]
Good news, everyone!  The extension now works with GNOME 45.  I'll upload the release to extensions.gnome.org for review, but in the meantime you can download the zip file directly from here:

https://github.com/jkitching/soft-brightness-plus/releases/tag/v35

**Comment by jkitching** [comment]
Closing this since there is a GNOME 45 compatible version on e.g.o now.
