### ISSUE TITLE
GNOME 46 support

### ISSUE THREAD

**Issue by Striffly** [jkitching/soft-brightness-plus#16]
There are breaking changes which will require a separate release for 46 :
See https://gjs.guide/extensions/upgrading/gnome-shell-46.html

**Comment by jkitching** [comment]
Thanks for the heads-up! I will take a look.

**Comment by jkitching** [comment]
Awaiting review here:
https://extensions.gnome.org/review/53134

In the meantime, feel free to clone the repo and build locally.

**Comment by jkitching** [comment]
Version 38 has been released and is live on e.g.o.

https://github.com/jkitching/soft-brightness-plus/releases/tag/v38
