### ISSUE TITLE
Gnome 46 Support Update We Want

### ISSUE THREAD

**Issue by Vickydmt** [jkitching/soft-brightness-plus#17]
Gnome Has Now Having New Version Bro So Please We Are Requesting The Gnome 46 Version Support Bro . Thank You For Your Software Brightness Plus❤️❤️❤️.

**Comment by jkitching** [comment]
Merging into existing issue: duplicate of #16.

Thanks For Your Support!

**Comment by jkitching** [comment]
Duplicate of #16
