### ISSUE TITLE
Gnome 45, extension not starting

### ISSUE THREAD

**Issue by TheNexter** [jkitching/soft-brightness-plus#18]
Error after installing :
`No signal 'child-added' on object 'MetaStage'`

Version :
Latest

How can i provide your more data about the bug ?

**Comment by jkitching** [comment]
Hi @TheNexter, thanks for letting me know about this error. Could you please let me know which version of GNOME you are using?

**Comment by TheNexter** [comment]
New version 16 is working fine in gnome 45 (not tested in gnome 46)
