### ISSUE TITLE
"quickSettings._brightness is undefined" error on login (Ubuntu 24.04)

### ISSUE THREAD

**Issue by ad203amiar** [jkitching/soft-brightness-plus#22]
It exits with some kind of problem in ubuntu 24.04 upon startup. Once I have logged in I have to do a manual stop and start, then it will work until computer is restarted.

**Comment by ad203amiar** [comment]
In case it helps:
May 04 09:24:33 Desktop gnome-shell[1814]: JS ERROR: TypeError: Main.panel.statusArea.quickSettings._brightness is undefined
                                           _enable@file:///home/"user"/.local/share/gnome-shell/extensions/soft-brightness-plus@joelkitching.com/extension.js:344:9
                                           enable/this._enableTimeoutId<@file:///home/"user"/.local/share/gnome-shell/extensions/soft-brightness-plus@joelkitching.com/extension.js:316:22
                                           @resource:///org/gnome/shell/ui/init.js:21:20

**Comment by jkitching** [comment]
Thanks for reporting this issue.
Does this error still occur when you disable all other extensions?

**Comment by ad203amiar** [comment]
yes. i disabled all other extensions including Ubuntu extensions in extension manager, and left only Soft Brightness Plus activated. then shutdown, and started, the result were the same .

**Comment by jkitching** [comment]
Hi @ad203amiar,

Would you mind trying this build to see if it fixes the issue?

[soft-brightness-plus@joelkitching.com.v40-RC1.shell-extension.zip](https://github.com/jkitching/soft-brightness-plus/files/15259444/soft-brightness-plus%40joelkitching.com.v40-RC1.shell-extension.zip)

Remove the existing extension first, and then install the ZIP version.  You can use something like this:

```
gnome-extensions install --force FILENAME.ZIP
```

**Comment by jkitching** [comment]
Thanks for testing!  v40 has been released with this fix, and is now published both on the "Releases" page and on extensions.gnome.org.
