### ISSUE TITLE
GNOME 47 support

### ISSUE THREAD

**Issue by dhra** [jkitching/soft-brightness-plus#27]
https://gjs.guide/extensions/upgrading/gnome-shell-47.html

**Comment by Striffly** [comment]
Seems to works without any changes except metadata.json
https://github.com/jkitching/soft-brightness-plus/pull/28

**Comment by jkitching** [comment]
Thanks so much @dhra for letting me know about the new version and @Striffly for the patch.  I've posted an update to e.g.o.
