### ISSUE TITLE
Idea: Brightness Follows Focus?

### ISSUE THREAD

**Issue by stevenjaycohen** [jkitching/soft-brightness-plus#7]
This might be outside of scope but you seem to already have almost everything needed to implement Brightness Follows Focus.

Like this: https://www.apptorium.com/screenfocus

It does seem like a different extension but I am guessing that you could reuse a lot of this code.

**Comment by jkitching** [comment]
Hi Steven,

Thanks for the idea!  It does seem like there could be some amount of overlap between the "follows focus" feature and the existing codebase.  However, with the handful of features that Soft Brightness Plus currently supports, it is already quite complex.  So I am thinking that your suggestion might make more sense as a separate extension. =)

Thanks for the support!

Joel
